-- BLO-19722: durable completion marker for worker-crash recovery.
--
-- `reconcileWorkerCrashedRuns` previously inferred "recovery finished" from the
-- existence of a retry child. That inference is wrong in both directions:
-- recovery deliberately completes *without* a retry when the agent is not
-- invokable (`enqueueProcessLossRetry` suppresses it and releases the issue
-- lock instead), so such a row would be replayed on every startup forever; and
-- the retry is committed *before* the lifecycle-event and agent-finalization
-- steps, so a crash in between made the row vanish from reconciliation while
-- those steps were still unfinished. Recording completion explicitly is the
-- only thing that gets both cases right.
--
-- Nullable, no default, so this is a catalog-only rewrite-free ADD COLUMN.
-- No backfill: `error_code = 'worker_crashed'` is introduced by the same change
-- that adds this column, so there are no pre-existing rows to classify.
--
-- Deliberately no supporting index. An earlier revision of this migration
-- added a partial index on (finished_at, id) and refused to run unless an
-- operator had precreated it with CREATE INDEX CONCURRENTLY. That protocol is
-- impossible: the index predicate references `crash_recovery_completed_at`,
-- which does not exist until this migration adds it, and Drizzle runs
-- migrations transactionally, so the refusal rolled the new column back — the
-- operator could never create the index the migration demanded, and a
-- populated database could never upgrade.
--
-- The index is not worth reintroducing. Its only reader is the startup
-- reconciliation scan in `reconcileWorkerCrashedRuns`, which runs once per
-- worker boot and is bounded by LIMIT 200. heartbeat_runs is ~221k rows /
-- 180 MB in production, so the unindexed scan costs well under a second, once,
-- at startup — cheaper than a non-concurrent index build's SHARE lock on the
-- deploy that introduces it, and far cheaper than an upgrade that cannot run.
ALTER TABLE "heartbeat_runs" ADD COLUMN IF NOT EXISTS "crash_recovery_completed_at" timestamp with time zone;
