-- BLO-21116 (Ally review on Blockcast/onprem-k8s#2013): the queued-run-age
-- gauge ages off heartbeat_runs.created_at, so a run promoted out of a long
-- scheduled_retry backoff inherits its full lifetime age instead of the time
-- it actually spent waiting for a dispatch slot. Nullable, no default: a fast
-- metadata-only ADD COLUMN, not a table rewrite. Left null for existing rows
-- and for fresh `queued` inserts -- refreshQueuedRunAgeMetrics falls back to
-- created_at via COALESCE, which is already correct for a brand-new row.
-- Only the specific transitions that put an *existing* row back into
-- `queued` after it was something else stamp this column with the
-- transition's own `now()`.
ALTER TABLE "heartbeat_runs" ADD COLUMN IF NOT EXISTS "queued_at" timestamp with time zone;
