import { readConfigFile } from "./config-file.js";
import { execFileSync } from "node:child_process";
import { existsSync, realpathSync, writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { randomBytes } from "node:crypto";
import { config as loadDotenv, parse as parseDotenv } from "dotenv";
import { resolvePaperclipEnvPath } from "./paths.js";
import { maybeRepairLegacyWorktreeConfigAndEnvFiles } from "./worktree-config.js";
import {
  AUTH_BASE_URL_MODES,
  BIND_MODES,
  DEPLOYMENT_EXPOSURES,
  DEPLOYMENT_MODES,
  SECRET_PROVIDERS,
  STORAGE_PROVIDERS,
  type BindMode,
  type AuthBaseUrlMode,
  type DeploymentExposure,
  type DeploymentMode,
  type SecretProvider,
  type StorageProvider,
  inferBindModeFromHost,
  resolveRuntimeBind,
  validateConfiguredBindMode,
} from "@paperclipai/shared";
import {
  resolveDefaultBackupDir,
  resolveDefaultEmbeddedPostgresDir,
  resolveDefaultSecretsKeyFilePath,
  resolveDefaultStorageDir,
  resolveHomeAwarePath,
} from "./home-paths.js";

const PAPERCLIP_ENV_FILE_PATH = resolvePaperclipEnvPath();
if (existsSync(PAPERCLIP_ENV_FILE_PATH)) {
  loadDotenv({ path: PAPERCLIP_ENV_FILE_PATH, override: false, quiet: true });
}

const CWD_ENV_PATH = resolve(process.cwd(), ".env");
const isSameFile = existsSync(CWD_ENV_PATH) && existsSync(PAPERCLIP_ENV_FILE_PATH)
  ? realpathSync(CWD_ENV_PATH) === realpathSync(PAPERCLIP_ENV_FILE_PATH)
  : CWD_ENV_PATH === PAPERCLIP_ENV_FILE_PATH;
if (!isSameFile && existsSync(CWD_ENV_PATH)) {
  loadDotenv({ path: CWD_ENV_PATH, override: false, quiet: true });
}

maybeRepairLegacyWorktreeConfigAndEnvFiles();

const TAILSCALE_DETECT_TIMEOUT_MS = 3000;

// Auto-generate PAPERCLIP_AGENT_JWT_SECRET on first boot so agents can authenticate
// without requiring a separate `pnpm paperclipai onboard` step.
if (!process.env.PAPERCLIP_AGENT_JWT_SECRET?.trim()) {
  const secret = randomBytes(32).toString("hex");
  const envDir = dirname(PAPERCLIP_ENV_FILE_PATH);
  mkdirSync(envDir, { recursive: true });
  const existing = existsSync(PAPERCLIP_ENV_FILE_PATH)
    ? parseDotenv(readFileSync(PAPERCLIP_ENV_FILE_PATH, "utf-8"))
    : {};
  existing.PAPERCLIP_AGENT_JWT_SECRET = secret;
  const lines = [
    "# Paperclip environment variables",
    "# Auto-generated by Paperclip server",
    ...Object.entries(existing).map(([k, v]) => `${k}=${v}`),
    "",
  ];
  writeFileSync(PAPERCLIP_ENV_FILE_PATH, lines.join("\n"), { mode: 0o600 });
  process.env.PAPERCLIP_AGENT_JWT_SECRET = secret;
}

type DatabaseMode = "embedded-postgres" | "postgres";

export interface Config {
  deploymentMode: DeploymentMode;
  deploymentExposure: DeploymentExposure;
  bind: BindMode;
  customBindHost: string | undefined;
  host: string;
  port: number;
  allowedHostnames: string[];
  authBaseUrlMode: AuthBaseUrlMode;
  authPublicBaseUrl: string | undefined;
  authDisableSignUp: boolean;
  databaseMode: DatabaseMode;
  databaseUrl: string | undefined;
  databaseMigrationUrl: string | undefined;
  embeddedPostgresDataDir: string;
  embeddedPostgresPort: number;
  databaseBackupEnabled: boolean;
  databaseBackupIntervalMinutes: number;
  databaseBackupRetentionDays: number;
  databaseBackupDir: string;
  // Merged-PR reconciler (BLO-9150): a scheduled sweep that backfills the no-ref
  // tail so the efficiency coverage % is measured, not a vacuous forward-only 100%.
  // Worker-tier only (gated on paperclipNodeRole !== "api" in index.ts).
  prReconcilerEnabled: boolean;
  prReconcilerIntervalMinutes: number;
  prReconcilerWindowDays: number;
  prReconcilerEnrichLoc: boolean;
  // Stranded-blocked-issue reconciler (BLO-21523 phase 1): drains issues stuck
  // `blocked` with zero unresolved blockers (last blocker cleared but `status`
  // was never recomputed). Worker-tier only, same rationale as the PR reconciler.
  strandedBlockedIssueReconcilerEnabled: boolean;
  strandedRecoveryHandBackDrainEnabled: boolean;
  strandedRecoveryHandBackMaxPerPass: number;
  strandedRecoveryHandBackIntervalMinutes: number;
  strandedBlockedIssueReconcilerIntervalMinutes: number;
  // Isolation-workspace reaper (BLO-31222): removes aged per-execution-workspace
  // scratch under `data/k8s-isolation/workspaces`, which had no retention path of
  // any kind and reached 406.7 GiB on a CephFS volume that ran out of headroom.
  // Worker-tier only. Opt-IN — it deletes irreversibly.
  isolationWorkspaceReaperEnabled: boolean;
  isolationWorkspaceReaperIntervalMinutes: number;
  isolationWorkspaceReaperMaxAgeDays: number;
  isolationWorkspaceReaperMaxDeletesPerTick: number;
  isolationWorkspaceReaperDryRun: boolean;
  // Human-gated ageing digest (BLO-29420): delivers the BLO-19130 ageing report
  // to a durable, human-assigned issue refreshed in place each period. Worker-tier
  // only, same rationale as the reconcilers above.
  humanGatedDigestEnabled: boolean;
  humanGatedDigestIntervalMinutes: number;
  humanGatedDigestPeriodDays: number;
  // Open-PR review-state reconciler (BLO-30259): persists pending review
  // requests + reviews so the ageing digest producer can be a pure DB read.
  // The producer runs under the digest's advisory lock and must not do network
  // I/O, so the GitHub polling lives here on its own interval.
  prReviewStateReconcilerEnabled: boolean;
  prReviewStateReconcilerIntervalMinutes: number;
  prReviewStateMaxPullRequestsPerRepo: number;
  // Approval-gate reconciler (BLO-29359): closes board approval cards whose
  // external GitHub gate has terminated, so an approver is never sent to a dead
  // run. Worker-tier only, same rationale as the PR reconciler.
  approvalGateReconcilerEnabled: boolean;
  approvalGateReconcilerIntervalMinutes: number;
  // Terminal-gate reconciler (BLO-27515): re-reads the PR gates a terminated
  // monitor declared, so a gate that resolves after the last poll is observed
  // without dispatching an assignee run. Worker-tier only.
  terminalGateReconcilerEnabled: boolean;
  terminalGateReconcilerIntervalMinutes: number;
  serveUi: boolean;
  uiDevMiddleware: boolean;
  secretsProvider: SecretProvider;
  secretsStrictMode: boolean;
  secretsMasterKeyFilePath: string;
  storageProvider: StorageProvider;
  storageLocalDiskBaseDir: string;
  storageS3Bucket: string;
  storageS3Region: string;
  storageS3Endpoint: string | undefined;
  storageS3Prefix: string;
  storageS3ForcePathStyle: boolean;
  feedbackExportBackendUrl: string | undefined;
  feedbackExportBackendToken: string | undefined;
  heartbeatSchedulerEnabled: boolean;
  heartbeatSchedulerIntervalMs: number;
  // Bounds stamped on newly-created wake_owner recovery actions. They remain
  // attached to the action for its lifetime, so a later config change cannot
  // extend a recovery attempt that has already started.
  recoveryActionMaxAttempts: number;
  recoveryActionTimeoutMs: number;
  // BLO-24782: how long a monitor that has already fired (`status: "triggered"`)
  // but has not been re-armed still counts as a live wake path. Past this bound
  // the recovery sweep treats the issue as having no wake path and escalates it
  // normally, which is what creates the `issue_recovery_actions` row that the
  // BLO-19124 reaper then bounds.
  //
  // Deliberately a separate knob from `recoveryActionTimeoutMs` even though the
  // defaults match: one bounds the lifetime of a recovery attempt that has
  // started, the other bounds how long an un-re-armed watch is believed. They
  // are independently choosable and collapsing them would make raising either
  // one silently move the other.
  lapsedMonitorGraceMs: number;
  // Process role for HA topology. When set to "api", the process serves
  // HTTP traffic only — no in-process plugin workers, no heartbeat
  // scheduler. When set to "worker", the process owns the heartbeat
  // scheduler + plugin workers (and may also serve HTTP — though typically
  // only an internal Service points at workers). When set to "all" (the
  // default), behavior is identical to pre-split single-pod paperclip:
  // one process owns everything.
  // Set via PAPERCLIP_NODE_ROLE env. Used by index.ts to gate which
  // subsystems start.
  paperclipNodeRole: "api" | "worker" | "all";
  // Base URL of the worker tier's internal Service, e.g.
  // "http://paperclip-workers:3100". Only consulted on the API tier
  // (PAPERCLIP_NODE_ROLE=api): worker-dependent plugin routes reverse-proxy
  // here so plugin lifecycle/bridge calls land on the pod that actually
  // owns pluginWorkerManager. Unset → those routes 503 via the API-tier
  // stub as before (no worker tier reachable). Set via
  // PAPERCLIP_WORKERS_INTERNAL_URL env.
  paperclipWorkersInternalUrl: string | null;
  companyDeletionEnabled: boolean;
  linearOAuthClientId: string;
  linearOAuthClientSecret: string;
  linearOAuthRedirectUri: string;
  // Shared secret configured on the GitHub webhook ("Secret" field in
  // the repo / org / app webhook settings). Used to verify
  // x-hub-signature-256 on POST /api/webhooks/github. When unset the
  // route refuses every request -- accepting unsigned webhooks would
  // let any caller drive paperclip wakes by impersonating GitHub.
  githubWebhookSecret: string;
  // Agent IDs that receive additional wakes on `pull_request.opened`,
  // `pull_request.ready_for_review`, and `pull_request_review.submitted`
  // events to drive PR review automation. New reviews are assigned to the
  // least-loaded active agent. When empty, the github-webhook
  // route only wakes the issue assignee (legacy behavior).
  githubPrReviewerAgentIds: string[];
  githubDependabotAgentId: string;
  githubDependabotMinSeverity: string;
  // GitHub App creds (from the `paperclip-github-app-creds` secret) used to mint
  // short-lived installation tokens so the server can authoritatively verify, via
  // the GitHub API, that a PR-review run actually left a review/comment before
  // flagging it `pr_review_output_missing`. All empty when unmounted -> the
  // verification is inert and the run falls back to the text-heuristic result.
  githubAppId: string;
  githubAppInstallationId: string;
  githubAppPrivateKey: string;
  // GitHub login of the PR-reviewer bot (the GitHub App's bot user, e.g.
  // "allyblockcast[bot]") used to filter reviews/comments during verification.
  prReviewerBotLogin: string;
  // Capture is deployed one rollout before authority processing so every API
  // replica durably records deliveries before any replica can activate the gate.
  githubReviewGateCaptureEnabled: boolean;
  // Repositories whose signed GitHub webhook deliveries drive review-gate
  // revocation and reconciliation. Empty keeps capture disabled.
  githubReviewGateEnabled: boolean;
  githubReviewGateRepositories: string[];
  // Deployment-pinned identity allowed to produce the protected status.
  // These are deliberately separate from the mounted credential fields so a
  // secret rotation cannot silently transfer review authority to another App.
  githubReviewGateExpectedAppId: string;
  githubReviewGateExpectedInstallationId: string;
  // Commit-status context to fail when a PR-review run exhausts its bounded
  // retry chain (e.g. "review/ally-complete"). A required status that is never
  // posted shows as "Expected — waiting for status" forever, so an exhausted
  // reviewer chain silently wedges the PR with no signal that nothing is
  // coming. Empty (the default) means the server posts no status at all —
  // the feature is opt-in per deployment because the context name belongs to
  // whoever owns the branch-protection rule, not to this server.
  prReviewGateStatusContext: string;
  // Commit-status context for comment-shaped Ally findings. Empty by default:
  // operators must opt in and make the context required in branch protection.
  prCommentReviewGateStatusContext: string;
  // Contexts this gate used to publish to and has since moved off. GitHub
  // commit statuses have no delete, so a context left behind by a rename keeps
  // showing its final write forever. After posting the live status the gate
  // also writes each of these a retirement pointer, which supersedes the stale
  // row in place and keeps any repo that still requires the old context
  // satisfied (BLO-29711).
  prCommentReviewGateRetiredStatusContexts: string[];
  telemetryEnabled: boolean;
}

function detectTailnetBindHost(): string | undefined {
  const explicit = process.env.PAPERCLIP_TAILNET_BIND_HOST?.trim();
  if (explicit) return explicit;

  try {
    const stdout = execFileSync("tailscale", ["ip", "-4"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
      timeout: TAILSCALE_DETECT_TIMEOUT_MS,
    });
    return stdout
      .split(/\r?\n/)
      .map((line) => line.trim())
      .find(Boolean);
  } catch {
    return undefined;
  }
}

/**
 * Configured PR reviewer agents, purely env-derived (no config-file input).
 *
 * Split out of loadConfig() so callers on hot paths can read it without paying
 * loadConfig()'s synchronous config-file read — the duplicate-PR-review issue
 * guard consults this on every agent-assigned issue creation (BLO-20526).
 */
export function readGithubPrReviewerAgentIds(): string[] {
  return [
    ...new Set(
      (
        process.env.PAPERCLIP_PR_REVIEWER_AGENT_IDS ??
        process.env.PAPERCLIP_PR_REVIEWER_AGENT_ID ??
        ""
      )
        .split(",")
        .map((value) => value.trim())
        .filter(Boolean),
    ),
  ];
}

/**
 * Largest delay `setTimeout`/`setInterval` accepts before Node coerces it.
 *
 * Above this, Node does *not* mean "never" — it emits `TimeoutOverflowWarning`
 * and sets the duration to **1 ms**, turning a period into a hot loop. This is
 * why every timer setting below needs an explicit ceiling and not merely a
 * finiteness check: `2 ** 31 - 1` ms is ~24.8 days, so an ordinary
 * minutes/milliseconds confusion reaches it with a finite value.
 */
export const MAX_TIMER_DELAY_MS = 2_147_483_647;

/** Ceiling shared by the minute-denominated timer periods (7d, well under the overflow). */
const TIMER_PERIOD_MINUTES_MAX = 7 * 24 * 60;

type NumericSettingBounds = {
  /** Used when no candidate is usable. Clamped like any other value. */
  fallback: number;
  min: number;
  max: number;
};

/**
 * Bounds for every numeric env override in this file, in one table so the
 * ceilings are reviewable together and a test can assert them without
 * restating the numbers.
 *
 * BLO-27641. The previous idiom at each of these sites was
 * `Math.max(FLOOR, Number(process.env.X) || DEFAULT)`, which looks doubly
 * guarded and is not: `Number("Infinity")` is truthy so `|| DEFAULT` never
 * fires, and `Math.max(FLOOR, Infinity)` is `Infinity`. The consequence splits
 * two ways depending on the consumer, and the second is the non-obvious one:
 *
 *  - **Comparison bounds** (`recoveryActionTimeoutMs`, `recoveryActionMaxAttempts`,
 *    the retention/window days) silently stop bounding. `recoveryActionTimeoutMs`
 *    is worse than "very long": it feeds `new Date(now + timeoutMs)`, and an
 *    infinite offset yields an *Invalid Date*, whose comparisons are all false —
 *    so the BLO-19124 bound is not loosened but absent.
 *  - **Timer periods** degrade to a 1 ms hot loop, not to "never" — see
 *    `MAX_TIMER_DELAY_MS`. `PAPERCLIP_DB_BACKUP_INTERVAL_MINUTES=Infinity` would
 *    schedule a database backup every millisecond: a self-inflicted outage
 *    rather than a disabled feature.
 */
export const NUMERIC_SETTING_BOUNDS = {
  databaseBackupIntervalMinutes: { fallback: 60, min: 1, max: TIMER_PERIOD_MINUTES_MAX },
  databaseBackupRetentionDays: { fallback: 7, min: 1, max: 3650 },
  prReconcilerIntervalMinutes: { fallback: 360, min: 1, max: TIMER_PERIOD_MINUTES_MAX },
  prReconcilerWindowDays: { fallback: 21, min: 1, max: 365 },
  strandedBlockedIssueReconcilerIntervalMinutes: {
    fallback: 15,
    min: 1,
    max: TIMER_PERIOD_MINUTES_MAX,
  },
  // BLO-31222. Daily is the right cadence: the cohort is defined in days, so a
  // tighter interval re-scans the same tree for nothing. The age floor is 7 —
  // below that a between-runs workspace looks reapable.
  isolationWorkspaceReaperIntervalMinutes: {
    fallback: 1440,
    min: 1,
    max: TIMER_PERIOD_MINUTES_MAX,
  },
  isolationWorkspaceReaperMaxAgeDays: { fallback: 30, min: 7, max: 3650 },
  isolationWorkspaceReaperMaxDeletesPerTick: { fallback: 200, min: 1, max: 10_000 },
  // BLO-19123. Per-tick ceiling on how many *distinct* rows the hand-back drain returns.
  //
  // The pass already had two per-issue guards — max 2 hand-backs per source issue and a 6h
  // source-scoped cooldown — but those bound how often a single row can bounce, not how many
  // rows move in a tick. Volume was governed only by the candidate limit's 500 default, so
  // the first tick after the drain flag flipped would have returned the entire backlog at
  // once (89 rows on the CEO alone, ~360 estate-wide when the plan was written).
  //
  // The original justification for metering was destination load: a single pass would take the
  // CTO from 369 open `todo` to 458, and at ~7.8 closures/day that is weeks of queue. That
  // reasoning was checked against the implementation on 2026-09-01 and does **not** hold at flip
  // time. The pass is ownership-only: it rewrites the owner on rows that are already `blocked`
  // (`recovery/service.ts`, `status: "blocked"`) and enqueues no wake, so at the moment the flag
  // flips it adds zero dispatchable work to any destination queue. The deferred load arrives
  // later, spread across the natural blocker-resolution rate — which is the rate at which that
  // work becomes real anyway.
  //
  // The meter is still correct, for a different and better reason: **blast-radius reversibility
  // against a bug in the gates.** A mis-routing defect in the eligibility or evidence checks
  // costs one bounded pass of rows, not the whole backlog. Do not read the collapse of the load
  // argument as grounds to widen the count or shorten the interval — the reason changed, the
  // requirement did not.
  //
  // Deferred rows are not lost. They are enumerated per row with reason
  // `candidate_limit_deferred` and picked up on the next tick, so a low ceiling trades drain
  // latency for observability rather than completeness. Ceiling is the service-side candidate
  // default, which is the most this ever did before it was metered.
  strandedRecoveryHandBackMaxPerPass: { fallback: 10, min: 1, max: 500 },
  // BLO-19123. How often that bounded pass is allowed to run — the other half of the meter.
  //
  // The count above bounds one pass; this bounds the rate. They are only useful together: the
  // drain rides the heartbeat tick (30s by default), so a count alone still returns ~90 rows
  // in under five minutes, which is the bulk move the meter exists to prevent. At the 60m
  // default, 10 rows/hour clears a ~90-row backlog over about nine passes.
  //
  // What those nine passes buy is a window to catch a *gate* defect — a row routed to the wrong
  // owner by a bug in the eligibility or evidence checks — while it has cost one batch instead
  // of the backlog. It is explicitly **not** about giving the destination queue time to absorb
  // load; that premise was checked and dropped (see the count above). An earlier draft of this
  // comment reasoned in "ticks" as if a tick were an observation interval: it is 30 seconds, so
  // nine of them is 4.5 minutes — a bulk return with extra steps, not a rate anyone can watch.
  // The hour is what makes the passes separable events.
  //
  // Floor of 1m rather than 0: "no delay" would silently restore the per-tick behaviour this
  // setting exists to remove, and an operator who wants the drain faster should raise the
  // count, where the blast radius of the change is legible.
  strandedRecoveryHandBackIntervalMinutes: {
    fallback: 60,
    min: 1,
    max: TIMER_PERIOD_MINUTES_MAX,
  },
  humanGatedDigestIntervalMinutes: {
    fallback: 360,
    min: 1,
    max: TIMER_PERIOD_MINUTES_MAX,
  },
  humanGatedDigestPeriodDays: { fallback: 7, min: 1, max: 365 },
  prReviewStateReconcilerIntervalMinutes: {
    fallback: 360,
    min: 1,
    max: TIMER_PERIOD_MINUTES_MAX,
  },
  prReviewStateMaxPullRequestsPerRepo: { fallback: 400, min: 1, max: 5000 },
  approvalGateReconcilerIntervalMinutes: {
    fallback: 10,
    min: 1,
    max: TIMER_PERIOD_MINUTES_MAX,
  },
  terminalGateReconcilerIntervalMinutes: {
    fallback: 10,
    min: 1,
    max: TIMER_PERIOD_MINUTES_MAX,
  },
  heartbeatSchedulerIntervalMs: { fallback: 30_000, min: 10_000, max: 24 * 60 * 60_000 },
  recoveryActionMaxAttempts: { fallback: 5, min: 1, max: 1_000 },
  recoveryActionTimeoutMs: {
    fallback: 6 * 60 * 60_000,
    min: 60 * 60_000,
    max: 7 * 24 * 60 * 60_000,
  },
  // BLO-24782. Floor well above a continuation run's turnaround: the BLO-16146
  // race this grace exists to avoid is measured in seconds, so no operator
  // setting may shrink it to where the sweep can beat a run that is legitimately
  // about to re-arm. Ceiling is 28x the default and far past the worst lapse ever
  // measured (~207h), so an override above it is asking for a bound that does not
  // bound — and `Infinity` in particular would restore the unbounded belief this
  // setting exists to remove, which `resolveNumericSetting` rejects outright.
  lapsedMonitorGraceMs: {
    fallback: 6 * 60 * 60_000,
    min: 15 * 60_000,
    max: 7 * 24 * 60 * 60_000,
  },
} as const satisfies Record<string, NumericSettingBounds>;

/**
 * The subset of the above consumed as a `setTimeout`/`setInterval` delay, with
 * the factor converting each to milliseconds. Declared rather than inferred so
 * the overflow invariant (`value * factor <= MAX_TIMER_DELAY_MS`) is checkable
 * for the minute-denominated settings, whose ceiling is not in the timer's unit.
 */
export const TIMER_SETTING_MS_FACTOR = {
  databaseBackupIntervalMinutes: 60_000,
  prReconcilerIntervalMinutes: 60_000,
  strandedBlockedIssueReconcilerIntervalMinutes: 60_000,
  isolationWorkspaceReaperIntervalMinutes: 60_000,
  // Minute-denominated like its neighbours, though it gates an elapsed-time comparison rather
  // than a `setInterval` delay. Registered anyway: the guard that requires this entry keys off
  // the name, and an unregistered minute setting is exactly the omission that guard exists to
  // catch — being exempt on a technicality would make the next real one invisible too.
  strandedRecoveryHandBackIntervalMinutes: 60_000,
  humanGatedDigestIntervalMinutes: 60_000,
  prReviewStateReconcilerIntervalMinutes: 60_000,
  approvalGateReconcilerIntervalMinutes: 60_000,
  terminalGateReconcilerIntervalMinutes: 60_000,
  heartbeatSchedulerIntervalMs: 1,
} as const satisfies Partial<Record<keyof typeof NUMERIC_SETTING_BOUNDS, number>>;

/**
 * What the call sites actually supply: env vars (`string | undefined`) and
 * file-config numbers. Narrower than `unknown` on purpose — `Number(true)` is
 * `1` and `Number([5])` is `5`, so a boolean or single-element array in a
 * config file would otherwise resolve to a plausible-looking interval instead
 * of falling through to the documented default.
 */
export type NumericSettingCandidate = string | number | null | undefined;

const numericSettingWarnings = new Set<string>();

/**
 * Test seam. The dedupe is deliberately process-global: an operator needs each
 * adjustment reported once at startup, not once per `loadConfig()` call (which
 * is un-memoized and re-invoked freely).
 */
export function resetNumericSettingWarnings(): void {
  numericSettingWarnings.clear();
}

function warnNumericSettingAdjustment(name: string | undefined, message: string): void {
  if (name === undefined) return;
  const key = `${name}:${message}`;
  if (numericSettingWarnings.has(key)) return;
  numericSettingWarnings.add(key);
  console.warn(`[config] ${name}: ${message}`);
}

/**
 * Render a rejected candidate for the operator.
 *
 * `JSON.stringify` maps every non-finite number to the string `null`, which
 * would make the reject warning unable to name the one input class it exists to
 * report: a config file carrying an overflowing literal parses to the *number*
 * `Infinity` (JSON has no `Infinity` token, but `JSON.parse("1e999")` yields
 * one), and the warning would then read `ignoring override null` and send the
 * operator looking for a literal `null` that is not in their file. Numbers are
 * therefore rendered with `String`; everything else keeps `JSON.stringify` so
 * the quoting still distinguishes the string `"abc"` from a bare number.
 */
function describeNumericCandidate(candidate: NumericSettingCandidate): string {
  return typeof candidate === "number" ? String(candidate) : JSON.stringify(candidate);
}

/**
 * Resolve the first usable candidate for a numeric setting, clamped to `[min, max]`.
 *
 * A candidate is usable only when it is finite and positive. Unusable
 * candidates fall through to the next one — matching the old `Number(x) || y`
 * chain, so a configured file-level fallback still wins over a bad env var —
 * and non-finite input therefore lands on the documented default rather than
 * being clamped to the ceiling. That distinction is deliberate: clamping
 * `Infinity` to `max` would silently read as an operator asking for the maximum,
 * where falling back keeps the startup banner honest about what is in effect.
 *
 * Two intentional behaviour changes, both of which an operator should audit on
 * upgrade — the second one affects input that was previously honoured verbatim:
 *
 *  1. A negative override used to survive `||` and get pulled up to the floor;
 *     it now falls back to the default instead.
 *  2. A *finite* override above the new ceiling is now clamped down to it. The
 *     clamps plausibly reachable in an existing deployment are:
 *       - `HEARTBEAT_SCHEDULER_INTERVAL_MS=172800000` (48h) → `86400000` (24h)
 *       - `PAPERCLIP_PR_RECONCILER_WINDOW_DAYS=730` → `365`
 *       - `PAPERCLIP_DB_BACKUP_RETENTION_DAYS=7300` → `3650`, which *shortens*
 *         retention, so the next prune deletes backups the operator asked to keep.
 *
 * Both are reported through `warnNumericSettingAdjustment` when `name` is
 * supplied, because the startup banner prints only the post-clamp number and so
 * cannot distinguish "operator asked for 365" from "operator asked for 730".
 */
export function resolveNumericSetting(
  candidates: readonly NumericSettingCandidate[],
  { fallback, min, max }: NumericSettingBounds,
  name?: string,
): number {
  for (const candidate of candidates) {
    if (candidate === undefined || candidate === null || candidate === "") continue;
    const parsed = Number(candidate);
    // Rejects NaN (unparseable), ±Infinity (including overflow literals such as
    // "1e999"), and anything non-positive.
    if (!Number.isFinite(parsed) || parsed <= 0) {
      warnNumericSettingAdjustment(
        name,
        `ignoring override ${describeNumericCandidate(candidate)} — not a finite positive number`,
      );
      continue;
    }
    const resolved = Math.min(max, Math.max(min, parsed));
    if (resolved !== parsed) {
      warnNumericSettingAdjustment(
        name,
        `override ${parsed} is outside [${min}, ${max}] and was clamped to ${resolved}`,
      );
    }
    return resolved;
  }
  return Math.min(max, Math.max(min, fallback));
}

export function loadConfig(): Config {
  const fileConfig = readConfigFile();
  const fileDatabaseMode =
    (fileConfig?.database.mode === "postgres" ? "postgres" : "embedded-postgres") as DatabaseMode;

  const fileDbUrl =
    fileDatabaseMode === "postgres"
      ? fileConfig?.database.connectionString
      : undefined;
  const fileDatabaseBackup = fileConfig?.database.backup;
  const fileSecrets = fileConfig?.secrets;
  const fileStorage = fileConfig?.storage;

  const providerFromEnvRaw = process.env.PAPERCLIP_SECRETS_PROVIDER;
  const providerFromEnv =
    providerFromEnvRaw && SECRET_PROVIDERS.includes(providerFromEnvRaw as SecretProvider)
      ? (providerFromEnvRaw as SecretProvider)
      : null;
  const providerFromFile = fileSecrets?.provider;
  const secretsProvider: SecretProvider = providerFromEnv ?? providerFromFile ?? "local_encrypted";

  const storageProviderFromEnvRaw = process.env.PAPERCLIP_STORAGE_PROVIDER;
  const storageProviderFromEnv =
    storageProviderFromEnvRaw && STORAGE_PROVIDERS.includes(storageProviderFromEnvRaw as StorageProvider)
      ? (storageProviderFromEnvRaw as StorageProvider)
      : null;
  const storageProvider: StorageProvider = storageProviderFromEnv ?? fileStorage?.provider ?? "local_disk";
  const storageLocalDiskBaseDir = resolveHomeAwarePath(
    process.env.PAPERCLIP_STORAGE_LOCAL_DIR ??
      fileStorage?.localDisk?.baseDir ??
      resolveDefaultStorageDir(),
  );
  const storageS3Bucket = process.env.PAPERCLIP_STORAGE_S3_BUCKET ?? fileStorage?.s3?.bucket ?? "paperclip";
  const storageS3Region = process.env.PAPERCLIP_STORAGE_S3_REGION ?? fileStorage?.s3?.region ?? "us-east-1";
  const storageS3Endpoint = process.env.PAPERCLIP_STORAGE_S3_ENDPOINT ?? fileStorage?.s3?.endpoint ?? undefined;
  const storageS3Prefix = process.env.PAPERCLIP_STORAGE_S3_PREFIX ?? fileStorage?.s3?.prefix ?? "";
  const storageS3ForcePathStyle =
    process.env.PAPERCLIP_STORAGE_S3_FORCE_PATH_STYLE !== undefined
      ? process.env.PAPERCLIP_STORAGE_S3_FORCE_PATH_STYLE === "true"
      : (fileStorage?.s3?.forcePathStyle ?? false);
  const feedbackExportBackendUrl =
    process.env.PAPERCLIP_FEEDBACK_EXPORT_BACKEND_URL?.trim() ||
    process.env.PAPERCLIP_TELEMETRY_BACKEND_URL?.trim() ||
    undefined;
  const feedbackExportBackendToken =
    process.env.PAPERCLIP_FEEDBACK_EXPORT_BACKEND_TOKEN?.trim() ||
    process.env.PAPERCLIP_TELEMETRY_BACKEND_TOKEN?.trim() ||
    undefined;

  const deploymentModeFromEnvRaw = process.env.PAPERCLIP_DEPLOYMENT_MODE;
  const deploymentModeFromEnv =
    deploymentModeFromEnvRaw && DEPLOYMENT_MODES.includes(deploymentModeFromEnvRaw as DeploymentMode)
      ? (deploymentModeFromEnvRaw as DeploymentMode)
      : null;
  const deploymentMode: DeploymentMode = deploymentModeFromEnv ?? fileConfig?.server.deploymentMode ?? "local_trusted";
  const strictModeFromEnv = process.env.PAPERCLIP_SECRETS_STRICT_MODE;
  const secretsStrictMode =
    strictModeFromEnv !== undefined
      ? strictModeFromEnv === "true"
      : (fileSecrets?.strictMode ?? deploymentMode === "authenticated");
  const deploymentExposureFromEnvRaw = process.env.PAPERCLIP_DEPLOYMENT_EXPOSURE;
  const deploymentExposureFromEnv =
    deploymentExposureFromEnvRaw &&
    DEPLOYMENT_EXPOSURES.includes(deploymentExposureFromEnvRaw as DeploymentExposure)
      ? (deploymentExposureFromEnvRaw as DeploymentExposure)
      : null;
  const deploymentExposure: DeploymentExposure =
    deploymentMode === "local_trusted"
      ? "private"
      : (deploymentExposureFromEnv ?? fileConfig?.server.exposure ?? "private");
  const bindFromEnvRaw = process.env.PAPERCLIP_BIND;
  const bindFromEnv =
    bindFromEnvRaw && BIND_MODES.includes(bindFromEnvRaw as BindMode)
      ? (bindFromEnvRaw as BindMode)
      : null;
  const configuredHost = process.env.HOST ?? fileConfig?.server.host ?? "127.0.0.1";
  const tailnetBindHost = detectTailnetBindHost();
  const bind =
    bindFromEnv ??
    fileConfig?.server.bind ??
    inferBindModeFromHost(configuredHost, { tailnetBindHost });
  const customBindHost = process.env.PAPERCLIP_BIND_HOST ?? fileConfig?.server.customBindHost;
  const authBaseUrlModeFromEnvRaw = process.env.PAPERCLIP_AUTH_BASE_URL_MODE;
  const authBaseUrlModeFromEnv =
    authBaseUrlModeFromEnvRaw &&
    AUTH_BASE_URL_MODES.includes(authBaseUrlModeFromEnvRaw as AuthBaseUrlMode)
      ? (authBaseUrlModeFromEnvRaw as AuthBaseUrlMode)
      : null;
  const publicUrlFromEnv = process.env.PAPERCLIP_PUBLIC_URL;
  const authPublicBaseUrlRaw =
    process.env.PAPERCLIP_AUTH_PUBLIC_BASE_URL ??
    process.env.BETTER_AUTH_URL ??
    process.env.BETTER_AUTH_BASE_URL ??
    publicUrlFromEnv ??
    fileConfig?.auth?.publicBaseUrl;
  const authPublicBaseUrl = authPublicBaseUrlRaw?.trim() || undefined;
  const authBaseUrlMode: AuthBaseUrlMode =
    authBaseUrlModeFromEnv ??
    fileConfig?.auth?.baseUrlMode ??
    (authPublicBaseUrl ? "explicit" : "auto");
  const disableSignUpFromEnv = process.env.PAPERCLIP_AUTH_DISABLE_SIGN_UP;
  const authDisableSignUp: boolean =
    disableSignUpFromEnv !== undefined
      ? disableSignUpFromEnv === "true"
      : (fileConfig?.auth?.disableSignUp ?? false);
  const allowedHostnamesFromEnvRaw = process.env.PAPERCLIP_ALLOWED_HOSTNAMES;
  const allowedHostnamesFromEnv = allowedHostnamesFromEnvRaw
    ? allowedHostnamesFromEnvRaw
      .split(",")
      .map((value) => value.trim().toLowerCase())
      .filter((value) => value.length > 0)
    : null;
  const publicUrlHostname = authPublicBaseUrl
    ? (() => {
      try {
        return new URL(authPublicBaseUrl).hostname.trim().toLowerCase();
      } catch {
        return null;
      }
    })()
    : null;
  const allowedHostnames = Array.from(
    new Set(
      [
        ...(allowedHostnamesFromEnv ?? fileConfig?.server.allowedHostnames ?? []),
        ...(publicUrlHostname ? [publicUrlHostname] : []),
      ]
        .map((value) => value.trim().toLowerCase())
        .filter(Boolean),
    ),
  );
  const companyDeletionEnvRaw = process.env.PAPERCLIP_ENABLE_COMPANY_DELETION;
  const companyDeletionEnabled =
    companyDeletionEnvRaw !== undefined
      ? companyDeletionEnvRaw === "true"
      : deploymentMode === "local_trusted";
  // PAPERCLIP_NODE_ROLE — defaults to "all" (single-pod, pre-split behavior).
  // Set to "api" for HTTP-only API replicas (no plugin workers, no scheduler).
  // Set to "worker" for the singleton workload that drives heartbeat dispatch
  // and hosts plugin workers. Unknown values fall back to "all" to preserve
  // safety (the worst case is a single process doing everything).
  const paperclipNodeRoleRaw = process.env.PAPERCLIP_NODE_ROLE ?? "all";
  const paperclipNodeRole: "api" | "worker" | "all" =
    paperclipNodeRoleRaw === "api" || paperclipNodeRoleRaw === "worker"
      ? paperclipNodeRoleRaw
      : "all";
  const databaseBackupEnabled =
    process.env.PAPERCLIP_DB_BACKUP_ENABLED !== undefined
      ? process.env.PAPERCLIP_DB_BACKUP_ENABLED === "true"
      : (fileDatabaseBackup?.enabled ?? true);
  const databaseBackupIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_DB_BACKUP_INTERVAL_MINUTES, fileDatabaseBackup?.intervalMinutes],
    NUMERIC_SETTING_BOUNDS.databaseBackupIntervalMinutes,
    "databaseBackupIntervalMinutes",
  );
  const databaseBackupRetentionDays = resolveNumericSetting(
    [process.env.PAPERCLIP_DB_BACKUP_RETENTION_DAYS, fileDatabaseBackup?.retentionDays],
    NUMERIC_SETTING_BOUNDS.databaseBackupRetentionDays,
    "databaseBackupRetentionDays",
  );
  const databaseBackupDir = resolveHomeAwarePath(
    process.env.PAPERCLIP_DB_BACKUP_DIR ??
      fileDatabaseBackup?.dir ??
      resolveDefaultBackupDir(),
  );
  // Merged-PR reconciler (BLO-9150). Enabled by default: the efficiency metric is
  // only honest once the no-ref tail is enumerated. Window defaults to 21d to
  // match the BLO-9103 cost-analysis window; interval defaults to 6h (merged PRs
  // are slow-moving, re-enumerating a 21d window every 6h is ample).
  const prReconcilerEnabled =
    process.env.PAPERCLIP_PR_RECONCILER_ENABLED !== undefined
      ? process.env.PAPERCLIP_PR_RECONCILER_ENABLED === "true"
      : true;
  const prReconcilerIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_PR_RECONCILER_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.prReconcilerIntervalMinutes,
    "prReconcilerIntervalMinutes",
  );
  const prReconcilerWindowDays = resolveNumericSetting(
    [process.env.PAPERCLIP_PR_RECONCILER_WINDOW_DAYS],
    NUMERIC_SETTING_BOUNDS.prReconcilerWindowDays,
    "prReconcilerWindowDays",
  );
  const prReconcilerEnrichLoc =
    process.env.PAPERCLIP_PR_RECONCILER_ENRICH_LOC !== undefined
      ? process.env.PAPERCLIP_PR_RECONCILER_ENRICH_LOC === "true"
      : true;
  // Stranded-blocked-issue reconciler (BLO-21523). Enabled by default: leaving
  // an issue permanently `blocked` after its last blocker clears is a silent
  // dispatch-reliability defect, not an opt-in feature. 15m default interval —
  // the backlog is small and re-checking is cheap (a guarded UPDATE that only
  // matches rows still `blocked` with zero unresolved blockers).
  const strandedBlockedIssueReconcilerEnabled =
    process.env.PAPERCLIP_STRANDED_BLOCKED_ISSUE_RECONCILER_ENABLED !== undefined
      ? process.env.PAPERCLIP_STRANDED_BLOCKED_ISSUE_RECONCILER_ENABLED === "true"
      : true;
  const strandedBlockedIssueReconcilerIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_STRANDED_BLOCKED_ISSUE_RECONCILER_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.strandedBlockedIssueReconcilerIntervalMinutes,
    "strandedBlockedIssueReconcilerIntervalMinutes",
  );

  // BLO-31222. Opt-IN, like `strandedRecoveryHandBack` and unlike the
  // reconcilers above: this removes directory trees irreversibly. Shipping it
  // dark keeps "deploy the code" and "delete a month of workspaces" as two
  // separate decisions, with a run in between to inspect what the predicate
  // matched. `..._DRY_RUN=true` performs that inspection without deleting.
  const isolationWorkspaceReaperEnabled =
    process.env.PAPERCLIP_ISOLATION_WORKSPACE_REAPER_ENABLED === "true";
  const isolationWorkspaceReaperDryRun =
    process.env.PAPERCLIP_ISOLATION_WORKSPACE_REAPER_DRY_RUN === "true";
  const isolationWorkspaceReaperIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_ISOLATION_WORKSPACE_REAPER_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.isolationWorkspaceReaperIntervalMinutes,
    "isolationWorkspaceReaperIntervalMinutes",
  );
  const isolationWorkspaceReaperMaxAgeDays = resolveNumericSetting(
    [process.env.PAPERCLIP_ISOLATION_WORKSPACE_REAPER_MAX_AGE_DAYS],
    NUMERIC_SETTING_BOUNDS.isolationWorkspaceReaperMaxAgeDays,
    "isolationWorkspaceReaperMaxAgeDays",
  );
  const isolationWorkspaceReaperMaxDeletesPerTick = resolveNumericSetting(
    [process.env.PAPERCLIP_ISOLATION_WORKSPACE_REAPER_MAX_DELETES_PER_TICK],
    NUMERIC_SETTING_BOUNDS.isolationWorkspaceReaperMaxDeletesPerTick,
    "isolationWorkspaceReaperMaxDeletesPerTick",
  );
  // BLO-19123. Opt-IN, unlike its sibling reconcilers above, and deliberately so: this pass
  // reassigns real in-flight work in bulk (~360 rows at the time of writing). Defaulting it
  // on would make "deploy the code" and "perform the data move" the same irreversible act,
  // with no run in between to re-derive the inventory the plan requires. Shipping it dark
  // keeps those two decisions separate — enabling the flag is the drain.
  const strandedRecoveryHandBackDrainEnabled =
    process.env.PAPERCLIP_STRANDED_RECOVERY_HAND_BACK_DRAIN_ENABLED === "true";
  // The rate, separate from the on/off above so it can be tuned without a second deploy:
  // the flag decides *whether* rows return, this decides *how fast*. See the bound's
  // rationale in NUMERIC_SETTING_BOUNDS.
  const strandedRecoveryHandBackMaxPerPass = resolveNumericSetting(
    [process.env.PAPERCLIP_STRANDED_RECOVERY_HAND_BACK_MAX_PER_PASS],
    NUMERIC_SETTING_BOUNDS.strandedRecoveryHandBackMaxPerPass,
    "strandedRecoveryHandBackMaxPerPass",
  );
  const strandedRecoveryHandBackIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_STRANDED_RECOVERY_HAND_BACK_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.strandedRecoveryHandBackIntervalMinutes,
    "strandedRecoveryHandBackIntervalMinutes",
  );
  // Human-gated ageing digest (BLO-29420). Enabled by default, consistent with
  // the reconcilers above: BLO-19130's escalation shipped inert and never fired
  // once, so an opt-in flag would just be a second way to stay silent. The sweep
  // maintains exactly one durable row per company and rewrites nothing when the
  // rendered body is unchanged, so a default-on tick is close to free.
  //
  // Interval (6h) is deliberately shorter than the period (7d): the period
  // decides what the digest *reports*, the interval decides how quickly a closed
  // or stale row is repaired. Refreshes are in-place description writes, so a
  // shorter interval costs no extra notifications.
  const humanGatedDigestEnabled =
    process.env.PAPERCLIP_HUMAN_GATED_DIGEST_ENABLED !== undefined
      ? process.env.PAPERCLIP_HUMAN_GATED_DIGEST_ENABLED === "true"
      : true;
  const humanGatedDigestIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_HUMAN_GATED_DIGEST_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.humanGatedDigestIntervalMinutes,
    "humanGatedDigestIntervalMinutes",
  );
  const humanGatedDigestPeriodDays = resolveNumericSetting(
    [process.env.PAPERCLIP_HUMAN_GATED_DIGEST_PERIOD_DAYS],
    NUMERIC_SETTING_BOUNDS.humanGatedDigestPeriodDays,
    "humanGatedDigestPeriodDays",
  );
  const prReviewStateReconcilerEnabled =
    process.env.PAPERCLIP_PR_REVIEW_STATE_RECONCILER_ENABLED !== undefined
      ? process.env.PAPERCLIP_PR_REVIEW_STATE_RECONCILER_ENABLED === "true"
      : true;
  const prReviewStateReconcilerIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_PR_REVIEW_STATE_RECONCILER_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.prReviewStateReconcilerIntervalMinutes,
    "prReviewStateReconcilerIntervalMinutes",
  );
  const prReviewStateMaxPullRequestsPerRepo = resolveNumericSetting(
    [process.env.PAPERCLIP_PR_REVIEW_STATE_MAX_PULL_REQUESTS_PER_REPO],
    NUMERIC_SETTING_BOUNDS.prReviewStateMaxPullRequestsPerRepo,
    "prReviewStateMaxPullRequestsPerRepo",
  );
  const approvalGateReconcilerEnabled =
    process.env.PAPERCLIP_APPROVAL_GATE_RECONCILER_ENABLED !== undefined
      ? process.env.PAPERCLIP_APPROVAL_GATE_RECONCILER_ENABLED === "true"
      : true;
  // 10 minutes: the cost of a stale card is an approver walking to a dead gate, and
  // the observed gate lifetimes that produced this defect were hours, not minutes.
  // Each sweep costs one GitHub REST call per pending gate card, so the population
  // (pending cards carrying a gate) bounds the rate-limit exposure, not the cadence.
  // That accounting is what makes an unbounded period dangerous here rather than
  // merely wrong: the 1 ms coercion turns the per-card cost into a REST flood.
  const approvalGateReconcilerIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_APPROVAL_GATE_RECONCILER_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.approvalGateReconcilerIntervalMinutes,
    "approvalGateReconcilerIntervalMinutes",
  );
  // Terminal-gate reconciler (BLO-27515). Enabled by default for the same
  // reason: a monitor gate that resolves while nothing is polling it is a
  // silent reliability defect, not an opt-in feature. 10m default — each pass
  // costs at most one GitHub read per distinct still-unresolved PR, and reads
  // stop entirely once a resolution is recorded.
  const terminalGateReconcilerEnabled =
    process.env.PAPERCLIP_TERMINAL_GATE_RECONCILER_ENABLED !== undefined
      ? process.env.PAPERCLIP_TERMINAL_GATE_RECONCILER_ENABLED === "true"
      : true;
  const terminalGateReconcilerIntervalMinutes = resolveNumericSetting(
    [process.env.PAPERCLIP_TERMINAL_GATE_RECONCILER_INTERVAL_MINUTES],
    NUMERIC_SETTING_BOUNDS.terminalGateReconcilerIntervalMinutes,
    "terminalGateReconcilerIntervalMinutes",
  );
  const bindValidationErrors = validateConfiguredBindMode({
    deploymentMode,
    deploymentExposure,
    bind,
    host: configuredHost,
    customBindHost,
  });
  if (bindValidationErrors.length > 0) {
    throw new Error(bindValidationErrors[0]);
  }
  const resolvedBind = resolveRuntimeBind({
    bind,
    host: configuredHost,
    customBindHost,
    tailnetBindHost,
  });
  if (resolvedBind.errors.length > 0) {
    throw new Error(resolvedBind.errors[0]);
  }

  const githubWebhookSecret = process.env.GITHUB_WEBHOOK_SECRET ?? "";
  const githubAppId = process.env.GITHUB_APP_ID ?? "";
  const githubAppInstallationId = process.env.GITHUB_APP_INSTALLATION_ID ?? "";
  const githubAppPrivateKey = (process.env.GITHUB_APP_PRIVATE_KEY ?? "").replace(/\\n/g, "\n");
  const githubReviewGateCaptureEnabled =
    process.env.PAPERCLIP_GITHUB_REVIEW_GATE_CAPTURE_ENABLED === "true";
  const githubReviewGateEnabled = process.env.PAPERCLIP_GITHUB_REVIEW_GATE_ENABLED === "true";
  const githubReviewGateRepositories = [
    ...new Set(
      (process.env.PAPERCLIP_GITHUB_REVIEW_GATE_REPOSITORIES ?? "")
        .split(",")
        .map((value) => value.trim())
        .filter(Boolean),
    ),
  ];
  const githubReviewGateExpectedAppId = (
    process.env.PAPERCLIP_GITHUB_REVIEW_GATE_EXPECTED_APP_ID ?? ""
  ).trim();
  const githubReviewGateExpectedInstallationId = (
    process.env.PAPERCLIP_GITHUB_REVIEW_GATE_EXPECTED_INSTALLATION_ID ?? ""
  ).trim();
  const prReviewGateStatusContext = (process.env.PAPERCLIP_PR_REVIEW_GATE_STATUS_CONTEXT ?? "").trim();
  if (githubReviewGateCaptureEnabled) {
    const missing = [
      ["GITHUB_WEBHOOK_SECRET", githubWebhookSecret.trim()],
      ["PAPERCLIP_GITHUB_REVIEW_GATE_REPOSITORIES", githubReviewGateRepositories.join(",")],
      ["PAPERCLIP_GITHUB_REVIEW_GATE_EXPECTED_APP_ID", githubReviewGateExpectedAppId],
      ["PAPERCLIP_GITHUB_REVIEW_GATE_EXPECTED_INSTALLATION_ID", githubReviewGateExpectedInstallationId],
      ["PAPERCLIP_PR_REVIEW_GATE_STATUS_CONTEXT", prReviewGateStatusContext],
    ].filter(([, value]) => !value).map(([name]) => name);
    if (missing.length > 0) {
      throw new Error(`GitHub review-gate capture is enabled but missing: ${missing.join(", ")}`);
    }
  }
  if (githubReviewGateEnabled) {
    if (!githubReviewGateCaptureEnabled) {
      throw new Error("GitHub review-gate authority requires durable capture to be enabled");
    }
    const missing = [
      ["GITHUB_APP_ID", githubAppId.trim()],
      ["GITHUB_APP_INSTALLATION_ID", githubAppInstallationId.trim()],
      ["GITHUB_APP_PRIVATE_KEY", githubAppPrivateKey.trim()],
    ].filter(([, value]) => !value).map(([name]) => name);
    if (missing.length > 0) {
      throw new Error(`GitHub review-gate authority is enabled but missing: ${missing.join(", ")}`);
    }
    if (
      githubAppId.trim() !== githubReviewGateExpectedAppId ||
      githubAppInstallationId.trim() !== githubReviewGateExpectedInstallationId
    ) {
      throw new Error("GitHub review-gate runtime credentials do not match the pinned App authority");
    }
  }

  return {
    deploymentMode,
    deploymentExposure,
    bind: resolvedBind.bind,
    customBindHost: resolvedBind.customBindHost,
    host: resolvedBind.host,
    port: Number(process.env.PORT) || fileConfig?.server.port || 3100,
    allowedHostnames,
    authBaseUrlMode,
    authPublicBaseUrl,
    authDisableSignUp,
    databaseMode: fileDatabaseMode,
    databaseUrl: process.env.DATABASE_URL ?? fileDbUrl,
    databaseMigrationUrl: process.env.DATABASE_MIGRATION_URL,
    embeddedPostgresDataDir: resolveHomeAwarePath(
      fileConfig?.database.embeddedPostgresDataDir ?? resolveDefaultEmbeddedPostgresDir(),
    ),
    embeddedPostgresPort: fileConfig?.database.embeddedPostgresPort ?? 54329,
    databaseBackupEnabled,
    databaseBackupIntervalMinutes,
    prReconcilerEnabled,
    prReconcilerIntervalMinutes,
    prReconcilerWindowDays,
    prReconcilerEnrichLoc,
    strandedBlockedIssueReconcilerEnabled,
    strandedRecoveryHandBackDrainEnabled,
    strandedRecoveryHandBackMaxPerPass,
    strandedRecoveryHandBackIntervalMinutes,
    strandedBlockedIssueReconcilerIntervalMinutes,
    isolationWorkspaceReaperEnabled,
    isolationWorkspaceReaperIntervalMinutes,
    isolationWorkspaceReaperMaxAgeDays,
    isolationWorkspaceReaperMaxDeletesPerTick,
    isolationWorkspaceReaperDryRun,
    humanGatedDigestEnabled,
    humanGatedDigestIntervalMinutes,
    humanGatedDigestPeriodDays,
    prReviewStateReconcilerEnabled,
    prReviewStateReconcilerIntervalMinutes,
    prReviewStateMaxPullRequestsPerRepo,
    approvalGateReconcilerEnabled,
    approvalGateReconcilerIntervalMinutes,
    terminalGateReconcilerEnabled,
    terminalGateReconcilerIntervalMinutes,
    databaseBackupRetentionDays,
    databaseBackupDir,
    serveUi:
      process.env.SERVE_UI !== undefined
        ? process.env.SERVE_UI === "true"
        : fileConfig?.server.serveUi ?? true,
    uiDevMiddleware: process.env.PAPERCLIP_UI_DEV_MIDDLEWARE === "true",
    secretsProvider,
    secretsStrictMode,
    secretsMasterKeyFilePath:
      resolveHomeAwarePath(
        process.env.PAPERCLIP_SECRETS_MASTER_KEY_FILE ??
          fileSecrets?.localEncrypted.keyFilePath ??
          resolveDefaultSecretsKeyFilePath(),
      ),
    storageProvider,
    storageLocalDiskBaseDir,
    storageS3Bucket,
    storageS3Region,
    storageS3Endpoint,
    storageS3Prefix,
    storageS3ForcePathStyle,
    feedbackExportBackendUrl,
    feedbackExportBackendToken,
    heartbeatSchedulerEnabled:
      // API role implies scheduler off regardless of HEARTBEAT_SCHEDULER_ENABLED.
      // Setting both lets `kubectl set env` toggles work the way operators expect.
      paperclipNodeRole === "api"
        ? false
        : process.env.HEARTBEAT_SCHEDULER_ENABLED !== "false",
    heartbeatSchedulerIntervalMs: resolveNumericSetting(
      [process.env.HEARTBEAT_SCHEDULER_INTERVAL_MS],
      NUMERIC_SETTING_BOUNDS.heartbeatSchedulerIntervalMs,
      "heartbeatSchedulerIntervalMs",
    ),
    // Preserve the existing wake-owner budget and six-hour horizon unless an
    // operator explicitly opts into new bounds through the configurable settings.
    recoveryActionMaxAttempts: resolveNumericSetting(
      [process.env.RECOVERY_ACTION_MAX_ATTEMPTS],
      NUMERIC_SETTING_BOUNDS.recoveryActionMaxAttempts,
      "recoveryActionMaxAttempts",
    ),
    recoveryActionTimeoutMs: resolveNumericSetting(
      [process.env.RECOVERY_ACTION_TIMEOUT_MS],
      NUMERIC_SETTING_BOUNDS.recoveryActionTimeoutMs,
      "recoveryActionTimeoutMs",
    ),
    lapsedMonitorGraceMs: resolveNumericSetting(
      [process.env.LAPSED_MONITOR_GRACE_MS],
      NUMERIC_SETTING_BOUNDS.lapsedMonitorGraceMs,
      "lapsedMonitorGraceMs",
    ),
    paperclipNodeRole,
    paperclipWorkersInternalUrl:
      process.env.PAPERCLIP_WORKERS_INTERNAL_URL?.trim().replace(/\/+$/, "") || null,
    companyDeletionEnabled,
    linearOAuthClientId: process.env.PAPERCLIP_LINEAR_CLIENT_ID ?? "",
    linearOAuthClientSecret: process.env.PAPERCLIP_LINEAR_CLIENT_SECRET ?? "",
    linearOAuthRedirectUri:
      process.env.PAPERCLIP_LINEAR_REDIRECT_URI ??
      `http://localhost:${Number(process.env.PORT) || fileConfig?.server.port || 3100}/api/auth/linear/callback`,
    githubWebhookSecret,
    // Agent IDs that receive additional wakes on `pull_request.opened`,
    // `pull_request.ready_for_review`, and `pull_request_review.submitted`
    // events to drive PR review automation. When unset, the github-webhook
    // route only wakes the issue assignee (legacy behavior). The reviewer
    // wake fires regardless of whether the PR branch references a paperclip
    // identifier, so PRs without a BLO-XXX in the branch/title/body still
    // get reviewed. The plural CSV setting takes precedence; the singular
    // setting remains supported for existing deployments.
    githubPrReviewerAgentIds: readGithubPrReviewerAgentIds(),
    githubDependabotAgentId: process.env.PAPERCLIP_DEPENDABOT_AGENT_ID ?? "",
    githubDependabotMinSeverity: process.env.PAPERCLIP_DEPENDABOT_MIN_SEVERITY ?? "high",
    // GitHub App creds for server-side installation-token minting (PR-review
    // evidence verification). `private_key.pem` may arrive with escaped "\n"
    // depending on how it is injected, so normalize them to real newlines.
    githubAppId,
    githubAppInstallationId,
    githubAppPrivateKey,
    prReviewerBotLogin: process.env.PAPERCLIP_PR_REVIEWER_BOT_LOGIN ?? "allyblockcast[bot]",
    prCommentReviewGateStatusContext: (process.env.PAPERCLIP_PR_COMMENT_REVIEW_GATE_STATUS_CONTEXT ?? "").trim(),
    githubReviewGateCaptureEnabled,
    githubReviewGateEnabled,
    githubReviewGateRepositories,
    githubReviewGateExpectedAppId,
    githubReviewGateExpectedInstallationId,
    prReviewGateStatusContext,
    prCommentReviewGateRetiredStatusContexts: [
      ...new Set(
        (process.env.PAPERCLIP_PR_COMMENT_REVIEW_GATE_RETIRED_STATUS_CONTEXTS ?? "")
          .split(",")
          .map((value) => value.trim())
          .filter(Boolean),
      ),
    ],
    telemetryEnabled: fileConfig?.telemetry?.enabled ?? true,
  };
}
