/**
 * The eligibility test for reviving a terminal issue from a deferred wake,
 * shared by the two components that promote one.
 *
 * `releaseIssueExecutionAndPromote` (`heartbeat.ts`) promotes when a run
 * finalizes on the issue; `drainLocklessDeferredIssueWakes`
 * (`recovery/service.ts`) promotes when no run ever will. They disagreed on
 * this predicate once already — the drain reproduced only the final `(user ||
 * issue_reopened_via_comment)` disjunct and was therefore strictly wider than
 * the path it claimed to mirror, classifying a run's own closing comment as a
 * human reopen request. Keeping one copy is what stops that recurring.
 *
 * This module is a leaf on purpose: `heartbeat.ts` already imports
 * `recovery/index.js`, so a predicate living in either of those files cannot be
 * imported by the other without a cycle.
 */

export const WAKE_COMMENT_IDS_KEY = "wakeCommentIds";

const readNonEmptyString = (value: unknown): string | null =>
  typeof value === "string" && value.trim().length > 0 ? value : null;

export function extractWakeCommentIds(
  contextSnapshot: Record<string, unknown> | null | undefined,
): string[] {
  const raw = contextSnapshot?.[WAKE_COMMENT_IDS_KEY];
  if (!Array.isArray(raw)) return [];
  const out: string[] = [];
  for (const entry of raw) {
    const value = readNonEmptyString(entry);
    if (!value || out.includes(value)) continue;
    out.push(value);
  }
  return out;
}

export function isTerminalIssueStatus(status: string | null | undefined): boolean {
  return status === "done" || status === "cancelled";
}

export interface DeferredWakeReopenEligibility {
  /** `issues.status` as read by the promoting component. */
  issueStatus: string | null | undefined;
  /** `extractWakeCommentIds(contextSnapshot)` — the comments this wake carries. */
  commentIds: readonly string[];
  /**
   * Whether every comment in {@link commentIds} was written by the agent this
   * wake targets, rather than by a human or another agent.
   *
   * The two callers derive this from different evidence and neither derivation
   * is available to the other:
   *
   * - The promoter has the finalizing run in hand and tests
   *   `issueComments.createdByRunId === run.id` — "the run that is ending right
   *   now wrote this".
   * - The drain has no finalizing run (that is its whole reason to exist) and
   *   resolves each comment's authoring run to its `agentId`, testing it
   *   against the wake's target agent — "this agent is waking itself about its
   *   own comment".
   *
   * They coincide on the case this guards, because the promoter's run belongs
   * to the agent being woken whenever the wake is self-directed. Where they can
   * differ is a comment authored by a *different* agent's run: the promoter
   * calls that self-authored (it is the finalizing run), the drain does not.
   * The drain's reading is the one that matches the hazard — BLO-23206 is an
   * agent waking itself, and a cross-agent handoff comment is explicitly a wake
   * to keep.
   */
  commentWakeIsSelfAuthored: boolean;
  /** `agent_wakeup_requests.requested_by_actor_type`. */
  requestedByActorType: string | null | undefined;
  /** The wake's effective reason, context snapshot first. */
  wakeReason: string | null | undefined;
}

/**
 * Only human/comment-reopen interactions should revive completed issues; system
 * follow-ups such as retry or cleanup wakes must not reopen closed work.
 *
 * All four conjuncts are load-bearing:
 *
 * - **a comment is referenced at all.** A wake carrying no comment id is not a
 *   follow-up on a conversation, so there is no request to revive anything.
 * - **not self-authored.** Local-CLI agents post comments under *user* auth, so
 *   a wake generated by the run that just closed the issue arrives as
 *   `requestedByActorType: "user"` and is otherwise indistinguishable from a
 *   real human follow-up. Without this conjunct the final disjunct admits it
 *   and the agent is re-queued onto the issue its own run just closed.
 * - **terminal.** Nothing to reopen otherwise.
 * - **human or comment-reopen origin.** A `system` retry or cleanup wake is
 *   not a request to resume the work.
 */
export function shouldReopenTerminalIssueForDeferredWake(
  input: DeferredWakeReopenEligibility,
): boolean {
  return (
    input.commentIds.length > 0 &&
    !input.commentWakeIsSelfAuthored &&
    isTerminalIssueStatus(input.issueStatus) &&
    (input.requestedByActorType === "user" ||
      input.wakeReason === "issue_reopened_via_comment")
  );
}
